version: "3.5"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - sinatra-network
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sinatra:
    build: ./sinatra
    container_name: sinatra_api
    restart: unless-stopped
    env_file: .env
    environment:
      SINATRA_ENV: development
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - sinatra-network
    volumes:
      - ./sinatra:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  db:

networks:
  sinatra-network:
    driver: bridge